[SQUASH] aidl: import the xiaomi vibrator
commit 5a53057b48a4b70ce8ebeb769c2ac5644f755880
Author: someone5678 <someone5678@users.noreply.github.com>
Date:   Thu Oct 26 08:12:54 2023 +0900

    vibrator: Add support for TEXTURE_TICK effect

    Change-Id: Iaca83c1c68a4bcf7c5aaf05fd3b71a286c97f300
    Signed-off-by: Richard Raya <rdxzv.dev@gmail.com>

commit 44b48740b28b98b5278801772e89d270d1d5654b
Author: Bartłomiej Rudecki <ejbtrd@gmail.com>
Date:   Sat Oct 7 22:48:24 2023 +0200

    vibrator: Fixup indentation

    - Vibrator.cpp:195:13: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
                return 0;

    Change-Id: Ie97d4715c400ffb543b8627824483c52fa9c811e
    Signed-off-by: Richard Raya <rdxzv.dev@gmail.com>

commit 72f66b124c907fdd54ac17afbabcca72d3f36e1a
Author: Richard Raya <rdxzv.dev@gmail.com>
Date:   Tue Jun 27 23:58:26 2023 -0300

    vibrator: Add support for drv2624:haptics

    Change-Id: Ic5ac8c4133db3f9e808cb3948ee8b7d0e8a97aea
    Signed-off-by: Richard Raya <rdxzv.dev@gmail.com>

commit 1212e3e5b216dda513fefdff6a337a05bf2e8615
Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
Date:   Mon Aug 14 08:22:57 2023 +0530

    vibrator: Create double click effect by "clicking" twice

    If the device decides to drop double click effect because it
    actually doesn't double click, repeat the click effect twice
    with a blank gap in between to stimulate double click.

    Change-Id: I34e7aed4de6e1398f6498a2eb4faaa51e135b0d0

commit 0e8aae2409eef29f093581d94d147cd70d4a4f06
Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
Date:   Fri Aug 11 19:33:04 2023 +0530

    vibrator: Fallback to click if an effect is missing

    On some device certain effects can be garbage to the point
    where its just better to use the default click effect.

    Change-Id: I047f72aaba2a1d56138a6431b5b96f0f626e2e83

commit 5cf8008243f5233335d31d0d2189875dc241b148
Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
Date:   Fri Aug 11 20:31:02 2023 +0530

    vibrator: Use a better check for primitive effects

    Some devices do have the primitive_duration node since its added
    in their kernel driver [1], but do not actually support primitive
    effects since they're not implemented in the devicetree (dtsi).

    Check if the click primitive effect is supported; if it isn't then
    its safe to assume the rest of the effects are unsupported as well.
    This is necessary so that AOSP can fall back to standard effects
    rather than simply failing to play the primitive effects.

    [1]: https://github.com/mikeNG/android_kernel_qcom_sm8450/commit/24a6bfeef28fdd6abb5161240fedd04659513b3e

    Change-Id: I6f1728092074474b366afeed24a5471773067e9c

commit 695c42750dafa5960c422387f05b0fed60c8a1f6
Author: Omkar Chandorkar <gotenksIN@aospa.co>
Date:   Thu Jun 22 08:50:01 2023 +0530

    vibrator: fix product makefile

    Change-Id: I2c6450546f70ea2fbe65d3a25bba180f4f03a661
    Signed-off-by: Omkar Chandorkar <gotenksIN@aospa.co>

commit 19d01360c176820bb4fd39ccdcaf3e4a07dc223f
Author: TheStrechh <TheStrechh@gmail.com>
Date:   Thu Jun 22 03:19:12 2023 +0530

    vibrator: Add support for awinic_haptic

    Change-Id: I08a4c0b060ac858bae9b8564a64ae2cd69b23159

commit ae113f3a61eb79c67c8b4c036031387378458e3f
Author: Arian <arian.kulmer@web.de>
Date:   Mon May 15 23:02:26 2023 +0200

    vibrator: Don't support compose effects if primitve_duration node does not exist

    Change-Id: Ic0cd6ea2220265168e47921292dc6bff4925d651

commit a4dd26515085fe83fd73d02bd7fd789e59f762c0
Author: Arian <arian.kulmer@web.de>
Date:   Thu Feb 24 17:52:15 2022 +0100

    vibrator: effect: Read vibration fifo data from vendor

    Change-Id: I58c74f01d75e8616fdb03c27e3dc4c4df6838faa

commit c325856f6e33f3a15c6eb1b2ace45b642a9b6988
Author: Arian <arian.kulmer@web.de>
Date:   Thu Feb 24 18:40:09 2022 +0100

    vibrator: Hook USE_EFFECT_STREAM up

    SOONG_CONFIG_NAMESPACES += XIAOMI_VIBRATOR
    SOONG_CONFIG_XIAOMI_VIBRATOR := USE_EFFECT_STREAM
    SOONG_CONFIG_XIAOMI_VIBRATOR_USE_EFFECT_STREAM ?= false

    Change-Id: I45f15112b16b04a9a012bf26e366aaebaa3a3bef

commit 84e33a5f97b9a303b84b926b5ed20884e57ae447
Author: Arian <arian.kulmer@web.de>
Date:   Mon May 15 10:33:46 2023 +0200

    vibrator: Add support for aw8697_haptic input device

    Change-Id: I58f5d0305ac688ba0b4d3ff5acfe04e5503b69aa

commit 267bff6c4311f2256943ca932492f89ebf38381b
Author: Arian <arian.kulmer@web.de>
Date:   Mon May 15 10:32:53 2023 +0200

    vibrator: Add support for aw8624_haptic input device

    Change-Id: Iff112c8ffa4462cfc30d06252b9cb5912f06f99a

commit 33d9fd53f534fabcc98399cf9181f4f38c7efb08
Author: Pig <pig.priv@gmail.com>
Date:   Sun Sep 20 12:45:49 2020 +0800

    vibrator: aidl: Simplify soc check and drop prop dep

    [npjohnson]: adapt to reflect 18.1 upstream merges as well as
    include now required headers.
    [ArianK16a]: Add new soc id's from https://git.codelinaro.org/clo/la/kernel/msm-5.15/-/blob/KERNEL.PLATFORM.2.0.r1-10800-kernel.0/drivers/soc/qcom/socinfo.c#L1086

    Change-Id: I8581d22deac451d0c44e4b3135d2729da2865a36

commit 343e061aa62de0708f43ef28c9149230791fdd31
Author: Arian <arian.kulmer@web.de>
Date:   Fri May 27 17:45:13 2022 +0200

    vibrator: Rename to avoid conflicts

    Change-Id: I0579eae1578a77481b5850febc89568fd7747fd7

commit a6efecbc5aabaf939769a53b764aac5f5d766f5a
Author: Arian <arian.kulmer@web.de>
Date:   Mon May 15 10:20:56 2023 +0200

    vibrator: Import from LA.VENDOR.13.2.0.r1-15400-KAILUA.QSSI14.0

    Change-Id: I47c315ce1900d486729e0bb501b53ae78265580e

Signed-off-by: David112x <86davidx64@gmail.com>